### PR TITLE
Upgrade Joomla to 3.7.5

### PR DESCRIPTION
**Pull request by frankmayer**

### CODE REVIEW

**Comment by frankmayer** [comment]
@mbabker I think you need to trigger some update, so that the docker hub/store gets the latest changes? In it's current form, the docker container hangs, when installing the database due to the bug in 3.7.4.

**Comment by mbabker** [comment]
Already done - https://hub.docker.com/_/joomla/

**Comment by frankmayer** [comment]
Ah, sorry I was checking: https://store.docker.com/images/joomla where it still shows 3.7.3 at the moment... I guess, it's not updated, yet.

**Comment by mbabker** [comment]
That one's not my account to update.  I submit the updates to their official images library, where it gets published from there is beyond me.

**Comment by frankmayer** [comment]
I think they are slowly transitioning from the hub to the store. So, you're right, it's their thing. :)

**Comment by zero-24** [comment]
Maybe it could be because of the installer issues with the 3.7.4?

**Comment by mbabker** [comment]
The tags list is up-to-date - https://store.docker.com/images/joomla/plans/6ad61f06-083d-4aa7-b452-a7c70f2e5378?tab=tags

The description looks to be a hardcoded copy/paste job.

**Comment by mbabker** [comment]
Either way, everything I am required to do as it relates to image updates is completed.  Anything beyond my scope (updating this repo, updating [the library image](https://github.com/docker-library/official-images/blob/master/library/joomla), or updating [the documentation](https://github.com/docker-library/docs/tree/master/joomla)) should be logged as an issue with Docker themselves.

**Pull request merged**
