### PR TITLE
Update to 3.9.18

### PR DESCRIPTION
**Pull request by J0WI**
https://github.com/docker-library/oi-janky-groovy/commit/cc435f9463538c7ebdb23b196adf6f1dc2ec7268

### CODE REVIEW

**Comment by mbabker** [comment]
That GitHub 2FA thing really bit people in the backside...

**Comment by J0WI** [comment]
@mbabker how to proceed with this?

**Comment by wilsonge** [comment]
I've escalated the docker library issue to Production

**Comment by wilsonge** [comment]
//cc @SniperSister @marcodings

**Pull request merged**
