### PR TITLE
Add architectures (fix #30)

### LINKED ISSUE #30: support arm64 architecture
I want to build this image on arm64 architecture but I'm not sure that can be support arm64 architecture https://github.com/joomla/joomla-cms/releases/download/3.7.4/Joomla_3.7.4-Stable-Full_Package.zip

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by mbabker** [comment]
Good news - finally got the new Jenkins CI system running with bashbrew in it to support this.

Bad news - applied the patch to my job there and when I ran the script I got this:

```sh
./generate-stackbrew-library.sh: line 116: parentRepoToArches[$variantParent]: unbound variable
```

**Comment by J0WI** [comment]
I just tested this again and it still works here :confused:

**Comment by J0WI** [comment]
Ah, I think your `bashbrew` is not in the `$PATH`.
https://github.com/joomla/docker-joomla/pull/63#issuecomment-395216445 could also do this btw.

**Comment by mbabker** [comment]
I don't think it's `$PATH`, `which bashbrew` resolves for both the root user and the Jenkins user account and running the generate file gives the same error on both accounts.

**Comment by J0WI** [comment]
I only get this error if `bashbrew` is not present.

**Comment by mbabker** [comment]
Well unless executing a shell script is somehow losing the `$PATH`...

**Comment by J0WI** [comment]
FYI, I just opened https://github.com/docker-library/oi-janky-groovy/pull/5, so @docker-library-bot can handle this (and it supports `bashbrew` out of the box).

**Pull request merged**
